# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[TASK] "

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "development"
    ignore:
      - dependency-name: "doctrine/dbal"
      - dependency-name: "phpunit/phpunit"
        versions: [ "^12.0" ]
      - dependency-name: "symfony/console"
      - dependency-name: "symfony/translation"
      - dependency-name: "symfony/yaml"
      - dependency-name: "typo3/cms-*"
      - dependency-name: "typo3/coding-standards"
    versioning-strategy: "increase"
    commit-message:
      prefix: "[TASK] "

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    commit-message:
      prefix: "[TASK] "
